lock_version = 1

[[packages]]
kind = "specialty"
name = "clothes"
format = "sw-public-package-v1"
version = "0.0.1"
digest = "sha256:90592acba5c1c1835af107e7e0e94b41e4a930b4c53861a117f9c8d567a0edf9"

[[packages]]
kind = "specialty"
name = "intimacy"
format = "sw-public-package-v1"
version = "0.0.1"
digest = "sha256:bb2cb6138247fdd2b82bc027e93a4ac344295be41cef0a30a06ff5e9b09c015e"

[[packages]]
kind = "specialty"
name = "plotlines"
format = "sw-public-package-v1"
version = "0.0.1"
digest = "sha256:f45b9067ca01daf804ae4b67201954fbd4428fd602ecb9f3a03b6426ab28cd98"

[[packages]]
kind = "specialty"
name = "sociology"
format = "sw-public-package-v1"
version = "0.0.1"
digest = "sha256:1911d1cf8399d9ce58578eab84cebdbe3dc05b01f07b7ed44d23e9027580cbb3"

[[packages]]
kind = "specialty"
name = "visuals"
format = "sw-public-package-v1"
version = "0.0.1"
digest = "sha256:20ddb992dc4cbeed23d291d69d7122e6d7b1ca463e646be1235d8b84daf9f9fe"

[[packages]]
kind = "zen"
name = "zen"
format = "sw-public-package-v1"
version = "0.0.1"
digest = "sha256:4337de648b4ef44d38a810891273bdbab1b20d332a1efea8cf39bdf5ff64e5a9"
